spring:
  application:
    name: orders

# H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    # url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

gateway:
  products:
    uri: http://localhost:8081/products